CREATE TABLE TAREFA(
IDTAREFA		UNIQUEIDENTIFIER	NOT NULL,
NOME			NVARCHAR(75)		NOT NULL,
DATA			DATE			NOT NULL,
HORA			TIME			NOT NULL,
DESCRICAO		NVARCHAR(150)		NOT NULL,
PRIORIDADE		INTEGER			NOT NULL,
PRIMARY KEY(IDTAREFA),
CHECK(PRIORIDADE IN(1,2,3))
)
GO